name: iOS IPA
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter build ios-framework --release
    - run: mkdir Payload
    - run: cp -r build/ios/iphoneos/Release-iphoneos/Runner.framework Payload/
    - run: zip -r app.ipa Payload/
    - uses: actions/upload-artifact@v4
      with:
        name: app.ipa
        path: app.ipa